# Generated by Django 4.1.1 on 2022-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emailid", models.CharField(max_length=100)),
                ("phoneNum", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
    ]
